### ISSUE TITLE
There is a problem with the result rendered by your code

### ISSUE THREAD

**Issue by yeluoo** [DongGeun-Yoon/Stereo-Magnification-Learning-view-synthesis-using-multiplane-images-MPIs-#2]
There is a problem with the result rendered by using your code, some of which are gray edges @DongGeun-Yoon @DongGeun-Yoon @

**Comment by DongGeun-Yoon** [comment]
Thank you for bringing this to our attention. The mentioned bug has been addressed and resolved!

**Comment by yeluoo** [comment]
Hello, are you still studying this method of generating a large baseline from a small baseline? You currently have a good method, which is a binocular method that I rarely research. Do you have a good paper to recommend?

**Comment by yeluoo** [comment]
When using my own data to perform psv (plane_sweep_torch_one)operations, do pose1 and pose2 need to be adjusted? If so, how should they be adjusted? The original default data is like this. I don’t understand why it is set like this.
`
Pose1 = '0.999947548 -0.001357046 -0.010151989 0.359417914 0.001413203 0.999983728 0.005526535 -0.003794850 0.010144324 -0.005540592 0.999933183 0.124850837'
Pose2 = '0.999962628 -0.002106981 -0.008386925 0.376296459 0.002151508 0.999983609 0.005303705 -0.001512435 0.008375612 -0.005321552 0.999950767 0.124671650'
`
@DongGeun-Yoon

**Comment by DongGeun-Yoon** [comment]
Sorry for the late reply. 

The code was trained with RealEstate-10k extracted with Colmap and follows the format of that dataset. 

You will need to fit the pose parameters the same as for Realestate-10k.

See the following links: [Realestate-10k](https://google.github.io/realestate10k/), [LLFF](https://github.com/Fyusion/LLFF).
